vich_uploader:
    db_driver: orm
    mappings:
        hotel_images:
            uri_prefix: /uploads/hotels
            upload_destination: '%kernel.project_dir%/public/uploads/hotels'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true
